name: Run FireflyIII Unit Support Tests

on:
  push:
    branches:
      - newfeature  # Change this to match your branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
          extensions: >-
              bcmath
              curl
              fileinfo
              iconv
              intl
              json
              sqlite3
              mbstring
              openssl
              pdo
              session
              simplexml
              sodium
              tokenizer
              xml
              xmlwriter



      - name: Copy .env example
        run: cp .env.example .env


      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist


      - name: "Create database file"
        run: |
          touch storage/database/database.sqlite
          wget -q https://github.com/firefly-iii/test-fixtures/raw/refs/heads/main/test-database.sqlite -O storage/database/database.sqlite


      - name: "Upgrades the database to the latest version"
        run:
          php artisan firefly-iii:upgrade-database


      - name: "Integrity Database Report"
        run: php artisan firefly-iii:report-integrity

      - name: Run PHPUnit tests in tests/unit/Support
        run: vendor/bin/phpunit tests/unit/Support/Calendar


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.34.0_Linux-64bit.deb

        # Build Docker image with timestamp tag
      - name: Build Docker image with timestamp tag
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          IMAGE_TAG="ameerm98/fireflyiii:$TIMESTAMP"
          docker build -t $IMAGE_TAG .

        # Scan Docker image for vulnerabilities
      - name: Scan Docker image for vulnerabilities with Trivy
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          IMAGE_TAG="ameerm98/fireflyiii:$TIMESTAMP"
          trivy image --exit-code 1 --no-progress $IMAGE_TAG


        # Push Docker image to DockerHub with the timestamp tag
      - name: Push Docker image to DockerHub
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          IMAGE_TAG="ameerm98/fireflyiii:$TIMESTAMP"
          docker push $IMAGE_TAG
